### ISSUE TITLE
Unexpected token '1fr'

### ISSUE THREAD

**Issue by gsvarma** [codacy/codacy-csslint#5]
Hello,

I noticed that Codacy reports an Unexpected token '1fr' on a valid CSS. Later found there is an [issue](https://github.com/CSSLint/csslint/issues/734) which is already raised at [CSSLint](https://github.com/CSSLint) in February but still no fix. I am wondering if there would be any fix from your side or at least a way to make [codacy check](https://github.com/marketplace/codacy) ignore [this](https://app.codacy.com/app/gsvarma/mWebsite/file/19575088602/issues/source?bid=7998060&fileBranchId=7998061#l105) particular line.

I look forward to your thoughts on this.
Thanks! in advance.

**Comment by rtfpessoa** [comment]
@gsvarma at the moment the best way would be to ignore the issue in the Codacy UI and hope for CSSLint to fix this.
